title: Thoughts
description: Personal Rambles
author: Suprita Shankar
github: https://github.com/supritashankar
about: I'm a software engineer based in silicon valley wishing to do good.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/supritashankar"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/suprita-shankar"
    - icon: fa-stack-exchange
      link: "https://stackexchange.com/users/1542956/suprita-shankar"
    - icon: fa-github
      link: "https://github.com/supritashankar"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://supritashankar.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
